sudo: false
addons:
  apt:
    packages:
    - git
language: java
jdk: oraclejdk8
env: TERM=dumb
# branches:
#   except:
#     - /^v\d+\.\d+\.\d+$/
before_install:
    - git fetch --unshallow
    - git config user.email "daplay@gmail.com"
    - git config user.name "Daniel Meneses"
    - git config url.https://.insteadOf git://
    - git checkout -qf $TRAVIS_BRANCH
install:
  - echo "skip default gradlew assemble"
  - echo "skip ${DANIEL}"
script:
  - ./gradlew release -x test --stacktrace -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password -PnexusUsername=${NEXUS_USERNAME} -PnexusPassword=${NEXUS_PASSWORD}
